### PR TITLE
Feat: footer

### LINKED ISSUE #6: Build out footer
## Content
* [x] Check-in with Haley
* [x] @AnthonyRollins Respond to questions and add updates to [lo-fi wireframes](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#)
* [x] Haley making edits to [content](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#) strategy
* [ ] ~Finalize homepage [content](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#) strategy~ Not needed for this ticket
* [x] Send footer content to designer
## Design
* [ ] ~Vyki to check in with Kristi~
* [x] Send designer final content / strategy
* [x] Approve final design drafts for footer
## Implementation
- [ ] Develop footer based on design specs

## Resources 
- Prior art / initial [Figma design](https://www.figma.com/file/fkRyBpWGDyaBh1kzaXIljo/Compiler-website?node-id=0%3A1) (not final, but to give an idea)
- [Lo-Fi Wireframe ](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#)

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #6 

Currently based off #30. Waiting for that to be merged first.

 Full page screenshot:   

image

### Proposals/questions for reviewers:
There are a few small differences between what I currently have vs. what's in the Figma.
 - **Contact section**: The Figma doesn't have a header for this section, but while working on it, I found that it looks better with a header.
    - **_Proposal_**: the Contact section has a header that says "Contact us"
 - **`hello@compiler.la` link**: The Figma shows this as a green link with a font of Source Code Pro. I think we did it like this because we were thinking of the original big-title link from the first version of the site. However, as I worked on the new link, I realized that all the other links on the site are white with Roboto as the font. The original big-title link was only styled with Source Code Pro because we were emulating the Compiler business card. Also, apparently the original link was white: https://deploy-preview-5--compilerla.netlify.app/
    - **_Proposal_**: the `hello@compiler.la` link is styled like all our other links on the site
 - **Section font**: The Figma shows the cert values as bold, white text at 18px. I'm not sure / don't remember our reasoning for this style. When I simply add the text for the cert values, they show up as normal, white text at 16px since this is the body style. This looks ok to me.
    - **_Proposal_**: no special styling for the cert values - they are styled the same as normal text on our site
 - **Social media icons**: I actually didn't notice this until I wrote out the notes above, but in our Figma, we added some space between the social media icons. I haven't made that change yet. Do y'all think this change is necessary?
    
 Let me know if you have any counter-proposals!

The original Figma mockup, from https://github.com/compilerla/compiler.la/issues/6#issuecomment-1256555734:   

image

### CODE REVIEW

**Comment by angela-tran** [comment]
Hmm, there's no Netlify preview on this PR. Maybe it's because the target branch is not `main`?

**Review by AnthonyRollins — CHANGES_REQUESTED** [review]
@angela-tran Answers to your proposals are below, but I was curious if there is a mobile screenshot I can get of the new footer, or I can just wait until the preview link is generated. I remembered our Figma files don't have mobile comps associated with them, so curious about what the footer looks like on mobile. 

**Contact section:**
I like the idea of a content section, but going back and forth if "Contact Us" should mirror the same color as the other headers "NAICS Codes," "Certifications," etc.
- [ ] Change font color for Contact Us to `#01B4CB`

**hello@compiler.la link:**
Let's keep as white, and I believe we had it `on-hover` change to the compiler green `#88B440` The font change also makes sense to me, so everything is the same.

**Section font:** 
No special styling works for me. (16px font).

**Social media icons:**
I believe we changed the spacing so it would match the full width of the "Contact Us" column, but I don't think we need it to. Curious if this helps on mobile or if there is any strong reason to match the spacing of the column @angela-tran @thekaveman

**Comment by thekaveman** [comment]
I think you'll have to open a brand new PR @angela-tran. Netlify only watches the `main` branch and this one probably was already ignored / passed over.

**Comment by angela-tran** [comment]
Ok, I'll try that out. Thanks @thekaveman

**Comment by angela-tran** [comment]
Sorry @AnthonyRollins and @thekaveman, the way I opened this pull request made it so the preview won't generate... see #32 instead. 🙏

**Pull request closed without merging**
