### PR TITLE
Feat: add link to capabilities statement

### LINKED ISSUE #9: Add capabilities statement
## Content
- [x] Finalize content/design for capabilities statement

## Design
- [x] #16
- [x] Add two new buttons; `Get in touch` and `Capabilities Statement`
- [x] `Capabilities Statement` button should use styling form [Figma design](https://www.figma.com/file/fkRyBpWGDyaBh1kzaXIljo/Compiler-website?node-id=20%3A391) and should be first and `left-aligned` link to `compiler.la/capabilitites`. On-hover change background to `opacity: 70%;`
- [x] `Get in touch` button should appear next to the Capabilities button with Compiler green `#88B440` outline and `#ffffff` font mailto link: `hello@compiler.la`. On-hover change background to `opacity: 70%;`
- [x] `We build software for the government.` change to an `h1` and moved just under the logo 

## Implementation
- [x] Add a download button for the capabilities statement to the preview site, based on future Figma designs
- [x] Redirect `https://compiler.la/capabilities` to the capabilities statement downloadable file

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #9

### CODE REVIEW

**Comment by AnthonyRollins** [comment]
@angela-tran `Get in touch` button should mirror the same on:hover effect as the `capabilities` button.

- [ ] Fill the button background `#88B440`
- [ ] Change text-color to `#000000`
- [ ] Change button color to `opacity: 70%`

**Comment by thekaveman** [comment]
@angela-tran @AnthonyRollins I updated the Figma mocks to reflect this secondary button hover style.

**Comment by angela-tran** [comment]
@AnthonyRollins Thanks for the clarifications! I believe I've got it all matching the Figma design now.

And speaking of that... I think now that we have a Figma design file, we should incorporate that into our workflow. Maybe we can try it out the next time there are new changes needed. 🙂

**Comment by AnthonyRollins** [comment]
Definitely - I think that's a great idea. We could also try out [Zeplin](https://zeplin.io/) if this would be a good use case for it.

**Review by AnthonyRollins — APPROVED** [review]
Everything looks good

**Pull request merged**
