### PR TITLE
Feat: company profile links

### LINKED ISSUE #11: Add link to Compiler's GitHub
Make it the 3rd line:

```
hello@compiler.la

we build software for the government

github.com/compilerla
```

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #11 

I went ahead and added links for our Twitter and LinkedIn profiles as well. Let me know if we want to keep it to just GitHub though!

Branding assets were sourced from:
 - https://github.com/logos
 - https://about.twitter.com/en/who-we-are/brand-toolkit
 - https://brand.linkedin.com/content/brand/global/en_us/index/visual-identity/logo

### CODE REVIEW

**Comment by angela-tran** [comment]
Oof, adding a third logo doesn't look good with the spacing I had added for two logos. Putting back in draft

**Review by thekaveman — APPROVED** [review]
This looks awesome! Nice job 👏 🚀

**Comment by AnthonyRollins** [comment]
@angela-tran Looks good to me, but I think we need to change the `hover-color` over the social media logos to `#ffffff` instead of `#88B440`. Unfortunately, based on the company's brand guides, I don't think we can change the color to our brand colors, even on hover. For instance, from[ Github's brand guide](https://github.com/logos):  

> Change the colors, dimensions or add your own text/images

**Review by AnthonyRollins — CHANGES_REQUESTED** [review]
@angela-tran Looks good to me, but I think we need to change the `hover-color` over the social media logos to `#ffffff` instead of `#88B440`. Unfortunately, based on the company's brand guides, I don't think we can change the color to our brand colors, even on hover. For instance, from[ Github's brand guide](https://github.com/logos):  

> Change the colors, dimensions or add your own text/images

**Review by AnthonyRollins — APPROVED** [review]
Looks good to me :)

**Pull request merged**
