### PR TITLE
Blog post: "Welcome to the Compiler blog"

### PR DESCRIPTION
**Pull request by angela-tran**
This is for https://app.clickup.com/t/86aywm4r2

The idea is to have a short and simple introduction to the blog

### CODE REVIEW

**Review by machikoyasuda — APPROVED** [review]
The post looks good to me. Now that this post is there, can we add the Blog link to the menu and make the Blog live? That could be part of this PR, or can be a separate PR, if we want to wait for Laney's post to also be up first. 

Only suggestion is to lowercase World.

**Comment by angela-tran** [comment]
@machikoyasuda and anyone else - how does this look?

image

**Review by machikoyasuda — APPROVED** [review]

**Comment by AnthonyRollins** [comment]
@angela-tran Looks good to me. I am unsure what everyone thinks, but the welcome post should go first and then be followed by @laneymangan's post.

As for the copy of the first welcome post, could we add a photo to the bottom, something like https://drive.google.com/open?id=1GnZZBkr7MRL525ByMgdfWlnmXrnAlrCg&usp=drive_fs. I am not tied to this particular photo, but it needs something.

**Comment by AnthonyRollins** [comment]
I am now realizing this has been posted, so I missed my chance, but if everyone thinks it makes sense to add a photo, I think it would be a nice touch.

**Comment by angela-tran** [comment]
@AnthonyRollins Sure, I can add a photo. For some reason, your link is just opening the May 2023 photos folder in Google Drive rather than any specific photo. Maybe you can tell me what the name of the file is? I'm interested to see which one you're thinking of 😄

**Comment by AnthonyRollins** [comment]
@angela-tran this [link](https://drive.google.com/file/d/1vpv1gsdT0L-4SiwK-ZXK778c2yT_ppmg/view?usp=drive_link) should work, but if it doesn't the file name is `NN1_0640.jpg`

**Comment by AnthonyRollins** [comment]
@angela-tran For some practice, I will create a PR and update this post with this photo unless you find a different image that you want to use.

**Comment by angela-tran** [comment]
@AnthonyRollins That sounds good to me. I think that's a great photo of everyone!

**Pull request merged**
