### PR TITLE
Feat: first-pass index.html

### LINKED ISSUE #2: Create initial Jekyll site structure and theme
## Context
Once #1 is done, this task is for setting up the basic structure of our Jekyll site. This includes finding or creating a basic theme for the website (can be very MVP).

Some potentially relevant Jekyll docs:
 - https://jekyllrb.com/docs/usage/
 - https://jekyllrb.com/docs/step-by-step/01-setup/#create-a-site

## Acceptance Criteria
- [x] The site can be viewed locally
- [x] There is a basic structure and theme in place

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #2 

### Summary
Adds a basic `index.html` file which mirrors our business cards with Compiler branding. Currently not utilizing any Jekyll features yet.

### CODE REVIEW

**Comment by angela-tran** [comment]
I might put this back into draft so that I can add media queries for mobile/tablet breakpoints in our CSS.

**Review by thekaveman — DISMISSED** [review]
Can we add the `C_` logo as a favicon please?

**Comment by vykster** [comment]
@thekaveman we actually have a favicon! 

[google link](https://drive.google.com/file/d/11Tzy4YfFzcpmEp1xMbmPKS_ifCibPn_h/view?usp=sharing)

**Comment by AnthonyRollins** [comment]
**Invert colors to mirror future website designs**
- [ ] Background color changed to `#262626` 
- [ ] Change font-color: `#ffffff` 
- [ ] Logo changed to white version with teal `#00B3CA` line "_." https://drive.google.com/open?id=1M0kuSPcwZkHP1pc2Fl_O6rP4z5u2oZoi&authuser=anthony%40compiler.la&usp=drive_fs
> I am not finding the white logo with the teal line in the branding folders, it should be the one in the drive link above, but it appears to be the wrong file.

- [ ] Icon inverted to https://drive.google.com/open?id=1k4OaFR6LG5gMIapGe8h55Zot25t__5V8&authuser=anthony%40compiler.la&usp=drive_fs

**Change email link `hello@compiler.la` color and text decoration**
- [ ] Change on-hover transition to green `#92B252`
- [ ] Add `text-decoration: underline`
> Adding a underline is important to [accessibility](https://webaim.org/blog/wcag-2-0-and-link-colors/)

**Comment by angela-tran** [comment]
@AnthonyRollins Thank you for the detailed list of changes! I was wondering where you found the values for `#00B3CA` as teal and `#92B252` as green.

I was referencing a PDF in Google Drive named `Compiler Style Guide V2.pdf`, but I'm not sure if that's the "official"/finalized resource. It has `#01B4CB` as teal and `#88B440` as green. 

Here's a [screenshot of the page](https://user-images.githubusercontent.com/25497886/173142872-f632452e-1473-4d2e-94fb-cae62f15d532.png) I was looking at... interestingly though, some colors in the PDF don't exactly match what's listed (see [teal](https://user-images.githubusercontent.com/25497886/173143063-328a46a6-0ab3-4e82-bae2-41787ff9b7e7.png) as an example).

**Comment by thekaveman** [comment]
Task linked: [CU-31era6j k](https://app.clickup.com/t/31era6j)

**Comment by thekaveman** [comment]
@AnthonyRollins here's a test comment to see if it pings you in Slack

**Comment by thekaveman** [comment]
@AnthonyRollins here's a test comment to see if it pings you in Slack

**Comment by AnthonyRollins** [comment]
I pulled the colors from the Figma designs: https://www.figma.com/file/fkRyBpWGDyaBh1kzaXIljo/Compiler-website?node-id=0%3A1. I would imagine the PDF brand guide has the color codes we should be using.

**Comment by angela-tran** [comment]
We're self-hosting the fonts since there isn't any performance gain to using CDN versions
https://wicki.io/posts/2020-11-goodbye-google-fonts/

**Review by thekaveman — APPROVED** [review]
🚀

**Pull request merged**
